apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
    - port: 9000
      name: s3
    - port: 9001
      name: console
  clusterIP: None
  selector:
    app: minio
