trino:
  catalogs:
    iceberg: |
      connector.name=iceberg

      iceberg.catalog.type=hive
      hive.metastore.uri=${ENV:LAB_HMS_URI}

      hive.s3.endpoint=${ENV:LAB_MINIO_ENDPOINT}
      hive.s3.aws-access-key=${ENV:LAB_MINIO_USERNAME}
      hive.s3.aws-secret-key=${ENV:LAB_MINIO_PASSWORD}
      hive.s3.path-style-access=true

  env:
    - name: LAB_HMS_URI
      value: thrift://hive-metastore.lab-dev.svc.cluster.local:9083

    - name: LAB_MINIO_ENDPOINT
      value: http://minio.minio.svc.cluster.local:9000

    - name: LAB_MINIO_USERNAME
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: username

    - name: LAB_MINIO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: password