trino:
  server:
    log:
      trino:
        level: DEBUG

  catalogs:
    iceberg: |
      connector.name=iceberg
      iceberg.catalog.type=hive_metastore
      hive.metastore.uri=${ENV:LAB_HMS_URI}

      fs.native-s3.enabled=true
      s3.endpoint=${ENV:LAB_MINIO_ENDPOINT}
      s3.region=us-east-1
      s3.path-style-access=true
      s3.aws-access-key=${ENV:LAB_MINIO_USERNAME}
      s3.aws-secret-key=${ENV:LAB_MINIO_PASSWORD}

  additionalConfigProperties:
    - http-server.process-forwarded=true

  accessControl:
    type: properties
    properties: |
      access-control.name=opa
      opa.policy.uri=http://opa.lab-dev.svc.cluster.local/v1/data/trino/allow
      opa.policy.row-filters-uri=http://opa.lab-dev.svc.cluster.local/v1/data/trino/row_filters

  env:
    - name: LAB_HMS_URI
      value: thrift://hive-metastore.lab-dev.svc.cluster.local:9083

    - name: LAB_MINIO_ENDPOINT
      value: http://minio.minio.svc.cluster.local:9000

    - name: LAB_MINIO_USERNAME
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: username

    - name: LAB_MINIO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: password