apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    log_format custom_body_log '$remote_addr - $remote_user [$time_local] '
                               '"$request" $status $body_bytes_sent '
                               '"$http_referer" "$http_user_agent" '
                               '$request_body';

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        access_log /dev/stdout custom_body_log;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /v1/data/trino/allow {
            default_type "application/json";
            return 200 '{"allow":true}';
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }