apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: main
          image: openpolicyagent/opa:1.7.1
          args:
            - run
            - --server
            - --addr=0.0.0.0:8181
            - /policy
          ports:
            - containerPort: 8181
              name: http
          volumeMounts:
            - name: opa-config-volume
              mountPath: /policy/trino.rego
              subPath: trino.rego
      volumes:
        - name: opa-config-volume
          configMap:
            name: opa-config
