apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: metastore
          image: naushadh/hive-metastore:1.0
          ports:
            - containerPort: 9083
          env:
            - name: DATABASE_HOST
              value: postgres.lab-dev.svc.cluster.local

            - name: DATABASE_PORT
              value: "5432"

            - name: DATABASE_DB
              value: lab_db

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: S3_ENDPOINT_URL
              value: http://minio.minio.svc.cluster.local:9000

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: username

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: password

            - name: S3_BUCKET
              value: lab

            - name: S3_PREFIX
              value: dev/hive-metastore
