apiVersion: v2
name: lab-dev-deployment
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: trino
    version: 1.40.0
    repository: https://trinodb.github.io/charts
