apiVersion: v1
kind: Service
metadata:
  name: jupyter-pyspark
  labels:
    app: jupyter-pyspark
spec:
  ports:
    - port: 8888
      name: jupyter
  clusterIP: None
  selector:
    app: jupyter-pyspark
