---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
spec:
  address: http://secret-manager-vault-internal.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cloudflare
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-tunnel-tokens
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  destination:
    create: true
    name: cloudflare-tunnel-tokens
  hmacSecretData: true
  mount: global
  path: cloudflare/tunnel-tokens
