apiVersion: v2
name: istio-ingress-deployment
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: gateway
    version: 1.27.1
    repository: https://istio-release.storage.googleapis.com/charts
