---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.29-alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.11.0-alpine
          ports:
            - containerPort: 4180
          args:
            - --config
            - /etc/oauth2-proxy.toml
          env:
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-credentials
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-credentials
                  key: cookie-secret
          volumeMounts:
            - name: oauth2-proxy-config-volume
              mountPath: /etc/oauth2-proxy.toml
              subPath: oauth2-proxy.toml
        - name: main
          image: ealen/echo-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
      volumes:
        - name: oauth2-proxy-config-volume
          configMap:
            name: oauth2-proxy-config
        - name: nginx-config-volume
          configMap:
            name: nginx-config
